/*
 * dd_plan.h - wirelog DD Execution Plan
 *
 * Copyright (C) CleverPlant
 * Licensed under LGPL-3.0
 * For commercial licenses, contact: inquiry@cleverplant.com
 *
 * INTERNAL HEADER - not installed, not part of public API.
 * Defines the DD execution plan: an abstract description of what
 * Differential Dataflow should execute, produced by translating
 * the stratified IR trees.
 *
 * ========================================================================
 * Overview
 * ========================================================================
 *
 * The DD plan is a C-side data structure that describes DD operations
 * without calling Rust or executing anything. It is produced by walking
 * the program's stratified IR trees and translating each IR node into
 * one or more DD operator descriptions.
 *
 * Pipeline position:
 *   Parse -> IR -> Stratify -> [DD Plan] -> (future) Rust FFI -> DD
 *
 * Translation rules (IR node -> DD op):
 *   SCAN      -> WL_FFI_DD_VARIABLE   (reference to input collection)
 *   PROJECT   -> WL_FFI_DD_MAP        (column projection)
 *   FILTER    -> WL_FFI_DD_FILTER     (predicate filter)
 *   JOIN      -> WL_FFI_DD_JOIN       (equijoin)
 *   ANTIJOIN  -> WL_FFI_DD_ANTIJOIN   (negation)
 *   SEMIJOIN  -> WL_FFI_DD_SEMIJOIN   (SIP pre-filter)
 *   AGGREGATE -> WL_FFI_DD_REDUCE     (group-by + aggregation)
 *   UNION     -> WL_FFI_DD_CONCAT + WL_FFI_DD_CONSOLIDATE (union + dedup)
 *   FLATMAP   -> (deferred to Phase 1, not generated by current IR)
 *
 * Stratum-aware generation:
 *   - EDB relations are collected as input collections
 *   - Each stratum produces a wl_ffi_dd_stratum_plan_t
 *   - Recursive strata (SCC size > 1 or self-loop) are marked
 *     is_recursive = true, indicating DD should wrap in iterate()
 *   - Strata are ordered: stratum 0 executes first
 *
 * ========================================================================
 * Memory Ownership
 * ========================================================================
 *
 * All pointer fields in DD ops are OWNED (deep copies of IR data).
 * The caller owns the plan returned by wl_ffi_dd_plan_generate() and must
 * free it with wl_ffi_dd_plan_free().  No pointers alias the input program.
 *
 * Ownership chain:
 *   wl_ffi_dd_plan_t
 *     -> edb_relations[]     (owned array of owned strings)
 *     -> strata[]            (owned array)
 *       -> relations[]       (owned array)
 *         -> name            (owned string)
 *         -> ops[]           (owned array)
 *           -> relation_name   (owned string, VARIABLE only)
 *           -> right_relation  (owned string, JOIN/ANTIJOIN only)
 *           -> left_keys[]     (owned array of owned strings, JOIN only)
 *           -> right_keys[]    (owned array of owned strings, JOIN only)
 *           -> project_indices (owned array, MAP only)
 *           -> filter_expr     (owned tree, FILTER only)
 *           -> group_by_indices(owned array, REDUCE only)
 *
 * ========================================================================
 * Error Handling
 * ========================================================================
 *
 * wl_ffi_dd_plan_generate() returns:
 *    0  success, *out is set
 *   -1  memory allocation failure (partial state cleaned up)
 *   -2  invalid input (NULL program, not stratified)
 *
 * On error, *out is unchanged (remains NULL if initialized to NULL).
 *
 * ========================================================================
 * Usage (internal)
 * ========================================================================
 *
 *   wl_ffi_dd_plan_t *plan = NULL;
 *   int rc = wl_ffi_dd_plan_generate(program, &plan);
 *   if (rc == 0) {
 *       wl_ffi_dd_plan_print(plan);  // debug
 *       // ... pass to FFI layer ...
 *       wl_ffi_dd_plan_free(plan);
 *   }
 */

#ifndef WIRELOG_FFI_DD_PLAN_H
#define WIRELOG_FFI_DD_PLAN_H

#include "../wirelog-types.h"

#include <stdbool.h>
#include <stdint.h>

/* Forward declarations */
struct wirelog_program;
struct wl_ir_expr;

/* ======================================================================== */
/* DD Operator Types                                                        */
/* ======================================================================== */

/**
 * wl_ffi_dd_op_type_t:
 *
 * Operator types in the DD execution plan.
 *
 * WL_FFI_DD_VARIABLE:    Reference to an input collection (EDB or IDB).
 * WL_FFI_DD_MAP:         Column projection / rename.
 * WL_FFI_DD_FILTER:      Predicate filter.
 * WL_FFI_DD_JOIN:        Equijoin on key columns.
 * WL_FFI_DD_ANTIJOIN:    Negation (antijoin).
 * WL_FFI_DD_REDUCE:      Aggregation (group-by + aggregate function).
 * WL_FFI_DD_CONCAT:      Union of multiple collections.
 * WL_FFI_DD_CONSOLIDATE: Deduplication / consolidation.
 * WL_FFI_DD_SEMIJOIN:    Semijoin (SIP pre-filter).
 */
typedef enum {
    WL_FFI_DD_VARIABLE,
    WL_FFI_DD_MAP,
    WL_FFI_DD_FILTER,
    WL_FFI_DD_JOIN,
    WL_FFI_DD_ANTIJOIN,
    WL_FFI_DD_REDUCE,
    WL_FFI_DD_CONCAT,
    WL_FFI_DD_CONSOLIDATE,
    WL_FFI_DD_SEMIJOIN,
} wl_ffi_dd_op_type_t;

/* ======================================================================== */
/* DD Operator Node                                                         */
/* ======================================================================== */

/**
 * wl_ffi_dd_op_t:
 *
 * Single operator in a DD execution plan.
 * Fields are used depending on the op type; unused fields are zero/NULL.
 * All pointer fields are OWNED (deep copies); freed by wl_ffi_dd_plan_free().
 *
 * Field usage by operator type:
 *
 *   VARIABLE:    relation_name
 *   MAP:         project_indices, project_count
 *   FILTER:      filter_expr
 *   JOIN:        right_relation, left_keys, right_keys, key_count
 *   ANTIJOIN:    right_relation, left_keys, right_keys, key_count
 *   REDUCE:      agg_fn, group_by_indices, group_by_count
 *   CONCAT:      (no fields)
 *   CONSOLIDATE: (no fields)
 *   SEMIJOIN:    right_relation, left_keys, right_keys, key_count,
 *                project_indices, project_count (left key column positions)
 *
 * @op:              Operator type.
 * @relation_name:   VARIABLE: source relation name (owned).
 * @right_relation:  JOIN/ANTIJOIN: right-side relation name (owned).
 * @left_keys:       JOIN/ANTIJOIN: left key column names (owned array of owned
 *                   strings).
 * @right_keys:      JOIN/ANTIJOIN: right key column names (owned array of owned
 *                   strings).
 * @key_count:       JOIN/ANTIJOIN: number of join keys.
 * @project_indices: MAP: output column index mapping (owned). May be NULL if
 *                   the IR used expression-based projection (project_exprs).
 * @project_count:   MAP: number of projected columns (always set, even when
 *                   project_indices is NULL).
 * @filter_expr:     FILTER: predicate expression tree (owned deep copy via
 *                   wl_ir_expr_clone). Never aliases the source IR.
 * @agg_fn:          REDUCE: aggregation function (count, sum, min, max).
 * @group_by_indices: REDUCE: grouping column indices (owned).
 * @group_by_count:  REDUCE: number of grouping columns.
 */
typedef struct {
    wl_ffi_dd_op_type_t op;

    char *relation_name;
    char *right_relation;

    char **left_keys;
    char **right_keys;
    uint32_t key_count;

    uint32_t *project_indices;
    uint32_t project_count;
    struct wl_ir_expr **project_exprs;

    struct wl_ir_expr *filter_expr;

    wirelog_agg_fn_t agg_fn;
    uint32_t *group_by_indices;
    uint32_t group_by_count;
} wl_ffi_dd_op_t;

/* ======================================================================== */
/* Per-Relation Plan                                                        */
/* ======================================================================== */

/**
 * wl_ffi_dd_relation_plan_t:
 *
 * Operator sequence for a single IDB relation within a stratum.
 *
 * @name:       Relation name (owned).
 * @ops:        Array of DD operators (owned).
 * @op_count:   Number of operators.
 * @op_capacity: Allocated capacity of ops array.
 */
typedef struct {
    char *name;
    wl_ffi_dd_op_t *ops;
    uint32_t op_count;
    uint32_t op_capacity;
} wl_ffi_dd_relation_plan_t;

/* ======================================================================== */
/* Stratum Plan                                                             */
/* ======================================================================== */

/**
 * wl_ffi_dd_stratum_plan_t:
 *
 * Execution plan for a single stratum.
 *
 * @stratum_id:     Stratum index (0 = executed first).
 * @is_recursive:   True if DD should wrap this stratum in iterate()
 *                  for fixed-point computation.
 * @relations:      Per-relation plans (owned array).
 * @relation_count: Number of relations in this stratum.
 */
typedef struct {
    uint32_t stratum_id;
    bool is_recursive;
    wl_ffi_dd_relation_plan_t *relations;
    uint32_t relation_count;
} wl_ffi_dd_stratum_plan_t;

/* ======================================================================== */
/* Full DD Plan                                                             */
/* ======================================================================== */

/**
 * wl_ffi_dd_plan_t:
 *
 * Complete DD execution plan for a stratified program.
 *
 * @strata:        Array of stratum plans (owned), ordered by execution.
 * @stratum_count: Number of strata.
 * @edb_relations: Names of EDB (input) relations (owned array of owned strings).
 * @edb_count:     Number of EDB relations.
 */
typedef struct {
    wl_ffi_dd_stratum_plan_t *strata;
    uint32_t stratum_count;
    char **edb_relations;
    uint32_t edb_count;
} wl_ffi_dd_plan_t;

/* ======================================================================== */
/* Internal API                                                             */
/* ======================================================================== */

/**
 * wl_ffi_dd_plan_generate:
 * @prog: Stratified program (must have is_stratified = true)
 * @out:  (out): On success, receives the generated plan.
 *
 * Generate a DD execution plan from a stratified program.
 * Walks each stratum's IR trees and translates them to DD operators.
 *
 * Returns:
 *    0: Success. *out is set to the plan.
 *   -1: Memory allocation error.
 *   -2: Invalid program (NULL, not stratified, etc.).
 */
int
wl_ffi_dd_plan_generate(const struct wirelog_program *prog, wl_ffi_dd_plan_t **out);

/**
 * wl_ffi_dd_plan_free:
 * @plan: (transfer full): Plan to free (NULL-safe).
 *
 * Free a DD plan and all owned memory.
 */
void
wl_ffi_dd_plan_free(wl_ffi_dd_plan_t *plan);

/**
 * wl_ffi_dd_op_type_str:
 * @type: DD operator type.
 *
 * Returns: Static string name for the operator type.
 */
const char *
wl_ffi_dd_op_type_str(wl_ffi_dd_op_type_t type);

/**
 * wl_ffi_dd_plan_print:
 * @plan: Plan to print (NULL-safe).
 *
 * Print a DD plan to stdout for debugging.
 */
void
wl_ffi_dd_plan_print(const wl_ffi_dd_plan_t *plan);

#endif /* WIRELOG_FFI_DD_PLAN_H */
