/*
 * dd_plan.h - wirelog DD Execution Plan
 *
 * Copyright (C) CleverPlant
 * Licensed under LGPL-3.0
 * For commercial licenses, contact: inquiry@cleverplant.com
 *
 * INTERNAL HEADER - not installed, not part of public API.
 * Defines the DD execution plan: an abstract description of what
 * Differential Dataflow should execute, produced by translating
 * the stratified IR trees.
 *
 * ========================================================================
 * Overview
 * ========================================================================
 *
 * The DD plan is a C-side data structure that describes DD operations
 * without calling Rust or executing anything. It is produced by walking
 * the program's stratified IR trees and translating each IR node into
 * one or more DD operator descriptions.
 *
 * Pipeline position:
 *   Parse -> IR -> Stratify -> [DD Plan] -> (future) Rust FFI -> DD
 *
 * Translation rules (IR node -> DD op):
 *   SCAN      -> WL_DD_VARIABLE   (reference to input collection)
 *   PROJECT   -> WL_DD_MAP        (column projection)
 *   FILTER    -> WL_DD_FILTER     (predicate filter)
 *   JOIN      -> WL_DD_JOIN       (equijoin)
 *   ANTIJOIN  -> WL_DD_ANTIJOIN   (negation)
 *   AGGREGATE -> WL_DD_REDUCE     (group-by + aggregation)
 *   UNION     -> WL_DD_CONCAT + WL_DD_CONSOLIDATE (union + dedup)
 *   FLATMAP   -> (deferred to Phase 1, not generated by current IR)
 *
 * Stratum-aware generation:
 *   - EDB relations are collected as input collections
 *   - Each stratum produces a wl_dd_stratum_plan_t
 *   - Recursive strata (SCC size > 1 or self-loop) are marked
 *     is_recursive = true, indicating DD should wrap in iterate()
 *   - Strata are ordered: stratum 0 executes first
 *
 * ========================================================================
 * Usage (internal)
 * ========================================================================
 *
 *   wl_dd_plan_t *plan = NULL;
 *   int rc = wl_dd_plan_generate(program, &plan);
 *   if (rc == 0) {
 *       wl_dd_plan_print(plan);  // debug
 *       // ... pass to FFI layer ...
 *       wl_dd_plan_free(plan);
 *   }
 */

#ifndef WIRELOG_DD_PLAN_H
#define WIRELOG_DD_PLAN_H

#include "../wirelog-types.h"

#include <stdbool.h>
#include <stdint.h>

/* Forward declarations */
struct wirelog_program;
struct wl_ir_expr;

/* ======================================================================== */
/* DD Operator Types                                                        */
/* ======================================================================== */

/**
 * wl_dd_op_type_t:
 *
 * Operator types in the DD execution plan.
 *
 * WL_DD_VARIABLE:    Reference to an input collection (EDB or IDB).
 * WL_DD_MAP:         Column projection / rename.
 * WL_DD_FILTER:      Predicate filter.
 * WL_DD_JOIN:        Equijoin on key columns.
 * WL_DD_ANTIJOIN:    Negation (antijoin).
 * WL_DD_REDUCE:      Aggregation (group-by + aggregate function).
 * WL_DD_CONCAT:      Union of multiple collections.
 * WL_DD_CONSOLIDATE: Deduplication / consolidation.
 */
typedef enum {
    WL_DD_VARIABLE,
    WL_DD_MAP,
    WL_DD_FILTER,
    WL_DD_JOIN,
    WL_DD_ANTIJOIN,
    WL_DD_REDUCE,
    WL_DD_CONCAT,
    WL_DD_CONSOLIDATE,
} wl_dd_op_type_t;

/* ======================================================================== */
/* DD Operator Node                                                         */
/* ======================================================================== */

/**
 * wl_dd_op_t:
 *
 * Single operator in a DD execution plan.
 * Fields are used depending on the op type; unused fields are zero/NULL.
 * All pointer fields are OWNED (deep copies); freed by wl_dd_plan_free().
 *
 * @op:              Operator type.
 * @relation_name:   VARIABLE: source relation name (owned).
 * @right_relation:  JOIN/ANTIJOIN: right-side relation name (owned).
 * @left_keys:       JOIN: left key column names (owned array of owned strings).
 * @right_keys:      JOIN: right key column names (owned array of owned strings).
 * @key_count:       JOIN: number of join keys.
 * @project_indices: MAP: output column index mapping (owned).
 * @project_count:   MAP: number of projected columns.
 * @filter_expr:     FILTER: predicate expression (owned deep copy).
 * @agg_fn:          REDUCE: aggregation function.
 * @group_by_indices: REDUCE: grouping column indices (owned).
 * @group_by_count:  REDUCE: number of grouping columns.
 */
typedef struct {
    wl_dd_op_type_t op;

    char *relation_name;
    char *right_relation;

    char **left_keys;
    char **right_keys;
    uint32_t key_count;

    uint32_t *project_indices;
    uint32_t project_count;

    struct wl_ir_expr *filter_expr;

    wl_agg_fn_t agg_fn;
    uint32_t *group_by_indices;
    uint32_t group_by_count;
} wl_dd_op_t;

/* ======================================================================== */
/* Per-Relation Plan                                                        */
/* ======================================================================== */

/**
 * wl_dd_relation_plan_t:
 *
 * Operator sequence for a single IDB relation within a stratum.
 *
 * @name:       Relation name (owned).
 * @ops:        Array of DD operators (owned).
 * @op_count:   Number of operators.
 * @op_capacity: Allocated capacity of ops array.
 */
typedef struct {
    char *name;
    wl_dd_op_t *ops;
    uint32_t op_count;
    uint32_t op_capacity;
} wl_dd_relation_plan_t;

/* ======================================================================== */
/* Stratum Plan                                                             */
/* ======================================================================== */

/**
 * wl_dd_stratum_plan_t:
 *
 * Execution plan for a single stratum.
 *
 * @stratum_id:     Stratum index (0 = executed first).
 * @is_recursive:   True if DD should wrap this stratum in iterate()
 *                  for fixed-point computation.
 * @relations:      Per-relation plans (owned array).
 * @relation_count: Number of relations in this stratum.
 */
typedef struct {
    uint32_t stratum_id;
    bool is_recursive;
    wl_dd_relation_plan_t *relations;
    uint32_t relation_count;
} wl_dd_stratum_plan_t;

/* ======================================================================== */
/* Full DD Plan                                                             */
/* ======================================================================== */

/**
 * wl_dd_plan_t:
 *
 * Complete DD execution plan for a stratified program.
 *
 * @strata:        Array of stratum plans (owned), ordered by execution.
 * @stratum_count: Number of strata.
 * @edb_relations: Names of EDB (input) relations (owned array of owned strings).
 * @edb_count:     Number of EDB relations.
 */
typedef struct {
    wl_dd_stratum_plan_t *strata;
    uint32_t stratum_count;
    char **edb_relations;
    uint32_t edb_count;
} wl_dd_plan_t;

/* ======================================================================== */
/* Internal API                                                             */
/* ======================================================================== */

/**
 * wl_dd_plan_generate:
 * @prog: Stratified program (must have is_stratified = true)
 * @out:  (out): On success, receives the generated plan.
 *
 * Generate a DD execution plan from a stratified program.
 * Walks each stratum's IR trees and translates them to DD operators.
 *
 * Returns:
 *    0: Success. *out is set to the plan.
 *   -1: Memory allocation error.
 *   -2: Invalid program (NULL, not stratified, etc.).
 */
int
wl_dd_plan_generate(const struct wirelog_program *prog, wl_dd_plan_t **out);

/**
 * wl_dd_plan_free:
 * @plan: (transfer full): Plan to free (NULL-safe).
 *
 * Free a DD plan and all owned memory.
 */
void
wl_dd_plan_free(wl_dd_plan_t *plan);

/**
 * wl_dd_op_type_str:
 * @type: DD operator type.
 *
 * Returns: Static string name for the operator type.
 */
const char *
wl_dd_op_type_str(wl_dd_op_type_t type);

/**
 * wl_dd_plan_print:
 * @plan: Plan to print (NULL-safe).
 *
 * Print a DD plan to stdout for debugging.
 */
void
wl_dd_plan_print(const wl_dd_plan_t *plan);

#endif /* WIRELOG_DD_PLAN_H */
