#!/usr/bin/env python3
"""
Setup uncrustify pre-commit hook for wirelog.

This script:
1. Checks if uncrustify is installed
2. Verifies .git/hooks/pre-commit exists and contains uncrustify check
3. Creates or updates the hook if necessary
4. Sets appropriate permissions

Called during: meson setup / meson compile
"""

import os
import sys
import subprocess
import stat
from pathlib import Path


def find_git_root():
    """Find the git repository root from current working directory."""
    current = Path.cwd()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    return None


def check_uncrustify_installed():
    """Check if uncrustify is installed and accessible."""
    try:
        result = subprocess.run(
            ["uncrustify", "--version"],
            capture_output=True,
            text=True,
            timeout=5
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def get_uncrustify_check_script():
    """Return the shell launcher for the transactional Uncrustify hook."""
    return '''#!/bin/sh
# WIRELOG_UNCRUSTIFY_HOOK_VERSION=2
# Auto-generated by scripts/setup_uncrustify_hook.py
set -eu

if command -v python3 >/dev/null 2>&1; then
    PYTHON=python3
elif command -v python >/dev/null 2>&1; then
    PYTHON=python
else
    echo "Error: Python 3 is required by the Uncrustify pre-commit hook" >&2
    exit 1
fi

GIT_ROOT=$(git rev-parse --show-toplevel) || exit 1
exec "$PYTHON" "$GIT_ROOT/scripts/ci/run-uncrustify-pre-commit.py"
'''


def setup_pre_commit_hook(git_root):
    """Create or update the .git/hooks/pre-commit hook."""
    try:
        result = subprocess.run(
            ["git", "-C", str(git_root), "rev-parse", "--git-path", "hooks"],
            check=True, capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=5)
        hooks_dir = Path(result.stdout.rstrip("\r\n"))
        if not hooks_dir.is_absolute():
            hooks_dir = git_root / hooks_dir
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        # Keep support for the standalone installer self-test and non-Git callers.
        hooks_dir = git_root / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    pre_commit_hook = hooks_dir / "pre-commit"
    hook_content = get_uncrustify_check_script()

    # Check if hook already exists
    if pre_commit_hook.exists():
        with open(pre_commit_hook, "r", encoding="utf-8") as f:
            existing_content = f.read()

        # Replace only a hook generated by this script. Preserve user hooks.
        if "# Auto-generated by setup_uncrustify_hook.py" not in existing_content:
            return True, "Existing custom pre-commit hook preserved"
        if "# WIRELOG_UNCRUSTIFY_HOOK_VERSION=2" in existing_content:
            return True, "Current generated pre-commit hook is already installed"

    # Write or overwrite hook
    try:
        # Issue #1464: the hook body is written with an explicit encoding.
        # Without it a console whose locale codec cannot encode the body
        # (cp949 on Windows) truncated the file to zero bytes and left a
        # non-executable hook that broke every commit.
        with open(pre_commit_hook, "w", encoding="utf-8") as f:
            f.write(hook_content)

        # Make executable
        st = os.stat(pre_commit_hook)
        os.chmod(pre_commit_hook, st.st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        return True, "Pre-commit hook installed successfully"
    except Exception as e:
        return False, f"Failed to install hook: {str(e)}"


def install_uncrustify():
    """Attempt to install uncrustify based on the platform."""
    import platform
    system = platform.system()

    print("\nAttempting to install uncrustify...")

    try:
        if system == "Darwin":  # macOS
            subprocess.run(["brew", "install", "uncrustify"], check=True)
            print("OK: uncrustify installed via Homebrew")
            return True

        elif system == "Windows":
            # Try Chocolatey first
            try:
                subprocess.run(["choco", "install", "-y", "uncrustify"], check=True, timeout=60)
                print("OK: uncrustify installed via Chocolatey")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            # Try Scoop
            try:
                subprocess.run(["scoop", "install", "uncrustify"], check=True, timeout=60)
                print("OK: uncrustify installed via Scoop")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            print("FAIL: Could not auto-install on Windows. Please install manually:")
            print("  Chocolatey: choco install uncrustify")
            print("  Scoop:      scoop install uncrustify")
            print("  Or download from: https://sourceforge.net/projects/uncrustify/files/")
            return False

        elif system == "Linux":
            # Try apt first (Ubuntu/Debian)
            try:
                subprocess.run(["sudo", "apt-get", "update"], check=True, timeout=30)
                subprocess.run(["sudo", "apt-get", "install", "-y", "uncrustify"], check=True, timeout=60)
                print("OK: uncrustify installed via apt")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            # Try pacman (Arch)
            try:
                subprocess.run(["sudo", "pacman", "-S", "--noconfirm", "uncrustify"], check=True, timeout=60)
                print("OK: uncrustify installed via pacman")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            # Try dnf (Fedora/RHEL)
            try:
                subprocess.run(["sudo", "dnf", "install", "-y", "uncrustify"], check=True, timeout=60)
                print("OK: uncrustify installed via dnf")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            # Try apk (Alpine)
            try:
                subprocess.run(["sudo", "apk", "add", "uncrustify"], check=True, timeout=60)
                print("OK: uncrustify installed via apk")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            print("FAIL: Could not auto-install on Linux. Please install manually:")
            print("  Debian/Ubuntu: sudo apt-get install uncrustify")
            print("  Arch:          sudo pacman -S uncrustify")
            print("  Fedora/RHEL:   sudo dnf install uncrustify")
            print("  Alpine:        sudo apk add uncrustify")
            return False

        else:
            print(f"FAIL: Unsupported platform: {system}")
            print("Please install uncrustify manually for your platform")
            return False

    except Exception as e:
        print(f"FAIL: Failed to install uncrustify: {str(e)}")
        return False


def main():
    """Main setup function."""
    # Find git root
    git_root = find_git_root()
    if not git_root:
        print("Error: Not in a git repository")
        return 1

    # Check if uncrustify is installed
    print("Checking for uncrustify installation...")
    if not check_uncrustify_installed():
        print("FAIL: uncrustify is NOT installed\n")

        # Try to install
        if not install_uncrustify():
            print("\nPlease install uncrustify manually:")
            print("  macOS:   brew install uncrustify")
            print("  Ubuntu:  sudo apt-get install uncrustify")
            print("  Arch:    sudo pacman -S uncrustify")
            print("  Fedora:  sudo dnf install uncrustify")
            print("  Alpine:  apk add uncrustify")
            print("\nThen run: meson setup build (or meson compile -C build)")
            return 1

        # Verify installation
        if not check_uncrustify_installed():
            print("FAIL: Installation verification failed. Please try manual installation.")
            return 1

    print("OK: uncrustify is installed")

    # Setup pre-commit hook
    success, message = setup_pre_commit_hook(git_root)
    print(f"{'OK' if success else 'FAIL'} {message}")

    if not success:
        return 1

    print("\nOK: Setup complete!")
    if message == "Existing custom pre-commit hook preserved":
        print("The custom pre-commit hook was preserved; integrate the generated formatter hook if needed.")
    else:
        print("The generated pre-commit hook formats staged C and header files as one batch.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
