#!/usr/bin/env python3
"""
Setup uncrustify pre-commit hook for wirelog.

This script:
1. Checks if uncrustify is installed
2. Verifies .git/hooks/pre-commit exists and contains uncrustify check
3. Creates or updates the hook if necessary
4. Sets appropriate permissions

Called during: meson setup / meson compile
"""

import os
import sys
import subprocess
import stat
from pathlib import Path


def find_git_root():
    """Find the git repository root from current working directory."""
    current = Path.cwd()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    return None


def check_uncrustify_installed():
    """Check if uncrustify is installed and accessible."""
    try:
        result = subprocess.run(
            ["uncrustify", "--version"],
            capture_output=True,
            text=True,
            timeout=5
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def get_uncrustify_check_script():
    """Return the shell script content for uncrustify pre-commit hook with auto-formatting."""
    return '''#!/bin/sh
# Pre-commit hook for automatic uncrustify formatting
# Auto-generated by setup_uncrustify_hook.py
#
# This hook automatically formats C/H files with uncrustify and re-stages them

if ! command -v uncrustify &> /dev/null; then
    echo "Error: uncrustify is not installed"
    echo "Please install uncrustify and try again:"
    echo "  macOS: brew install uncrustify"
    echo "  Linux: apt-get install uncrustify (or equivalent)"
    exit 1
fi

# Get list of staged C/H files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\\.(c|h)$')

if [ -z "$STAGED_FILES" ]; then
    exit 0
fi

# Find git root directory
GIT_ROOT=$(git rev-parse --show-toplevel)
UNCRUSTIFY_CONFIG="$GIT_ROOT/uncrustify.cfg"

if [ ! -f "$UNCRUSTIFY_CONFIG" ]; then
    echo "Warning: uncrustify.cfg not found at $UNCRUSTIFY_CONFIG"
    exit 0
fi

echo "Auto-formatting C code with uncrustify..."
FORMATTED_FILES=0

for file in $STAGED_FILES; do
    if [ -f "$file" ]; then
        # Create temp formatted version
        uncrustify -c "$UNCRUSTIFY_CONFIG" -f "$file" > /tmp/uncrustify_formatted.tmp 2>/dev/null

        # Check if formatting changed
        if ! diff -q "$file" /tmp/uncrustify_formatted.tmp > /dev/null 2>&1; then
            # Apply formatted version
            cp /tmp/uncrustify_formatted.tmp "$file"
            echo "  ✓ $file - formatted and re-staged"

            # Re-stage the formatted file
            git add "$file"
            FORMATTED_FILES=$((FORMATTED_FILES + 1))
        else
            echo "  ✓ $file"
        fi
    fi
done

rm -f /tmp/uncrustify_formatted.tmp

if [ $FORMATTED_FILES -gt 0 ]; then
    echo ""
    echo "Success: $FORMATTED_FILES file(s) formatted and re-staged"
    echo "Review changes and commit again if satisfied."
fi

exit 0
'''


def setup_pre_commit_hook(git_root):
    """Create or update the .git/hooks/pre-commit hook."""
    hooks_dir = git_root / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    pre_commit_hook = hooks_dir / "pre-commit"
    hook_content = get_uncrustify_check_script()

    # Check if hook already exists
    if pre_commit_hook.exists():
        with open(pre_commit_hook, "r") as f:
            existing_content = f.read()

        # Check if uncrustify check is already present
        if "uncrustify" in existing_content:
            return True, "Pre-commit hook already contains uncrustify check"

    # Write or overwrite hook
    try:
        with open(pre_commit_hook, "w") as f:
            f.write(hook_content)

        # Make executable
        st = os.stat(pre_commit_hook)
        os.chmod(pre_commit_hook, st.st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        return True, "Pre-commit hook installed successfully"
    except Exception as e:
        return False, f"Failed to install hook: {str(e)}"


def install_uncrustify():
    """Attempt to install uncrustify based on the platform."""
    import platform
    system = platform.system()

    print("\nAttempting to install uncrustify...")

    try:
        if system == "Darwin":  # macOS
            subprocess.run(["brew", "install", "uncrustify"], check=True)
            print("✓ uncrustify installed via Homebrew")
            return True

        elif system == "Windows":
            # Try Chocolatey first
            try:
                subprocess.run(["choco", "install", "-y", "uncrustify"], check=True, timeout=60)
                print("✓ uncrustify installed via Chocolatey")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            # Try Scoop
            try:
                subprocess.run(["scoop", "install", "uncrustify"], check=True, timeout=60)
                print("✓ uncrustify installed via Scoop")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            print("✗ Could not auto-install on Windows. Please install manually:")
            print("  Chocolatey: choco install uncrustify")
            print("  Scoop:      scoop install uncrustify")
            print("  Or download from: https://sourceforge.net/projects/uncrustify/files/")
            return False

        elif system == "Linux":
            # Try apt first (Ubuntu/Debian)
            try:
                subprocess.run(["sudo", "apt-get", "update"], check=True, timeout=30)
                subprocess.run(["sudo", "apt-get", "install", "-y", "uncrustify"], check=True, timeout=60)
                print("✓ uncrustify installed via apt")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            # Try pacman (Arch)
            try:
                subprocess.run(["sudo", "pacman", "-S", "--noconfirm", "uncrustify"], check=True, timeout=60)
                print("✓ uncrustify installed via pacman")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            # Try dnf (Fedora/RHEL)
            try:
                subprocess.run(["sudo", "dnf", "install", "-y", "uncrustify"], check=True, timeout=60)
                print("✓ uncrustify installed via dnf")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            # Try apk (Alpine)
            try:
                subprocess.run(["sudo", "apk", "add", "uncrustify"], check=True, timeout=60)
                print("✓ uncrustify installed via apk")
                return True
            except (subprocess.CalledProcessError, FileNotFoundError):
                pass

            print("✗ Could not auto-install on Linux. Please install manually:")
            print("  Debian/Ubuntu: sudo apt-get install uncrustify")
            print("  Arch:          sudo pacman -S uncrustify")
            print("  Fedora/RHEL:   sudo dnf install uncrustify")
            print("  Alpine:        sudo apk add uncrustify")
            return False

        else:
            print(f"✗ Unsupported platform: {system}")
            print("Please install uncrustify manually for your platform")
            return False

    except Exception as e:
        print(f"✗ Failed to install uncrustify: {str(e)}")
        return False


def main():
    """Main setup function."""
    # Find git root
    git_root = find_git_root()
    if not git_root:
        print("Error: Not in a git repository")
        return 1

    # Check if uncrustify is installed
    print("Checking for uncrustify installation...")
    if not check_uncrustify_installed():
        print("✗ uncrustify is NOT installed\n")

        # Try to install
        if not install_uncrustify():
            print("\nPlease install uncrustify manually:")
            print("  macOS:   brew install uncrustify")
            print("  Ubuntu:  sudo apt-get install uncrustify")
            print("  Arch:    sudo pacman -S uncrustify")
            print("  Fedora:  sudo dnf install uncrustify")
            print("  Alpine:  apk add uncrustify")
            print("\nThen run: meson setup build (or meson compile -C build)")
            return 1

        # Verify installation
        if not check_uncrustify_installed():
            print("✗ Installation verification failed. Please try manual installation.")
            return 1

    print("✓ uncrustify is installed")

    # Setup pre-commit hook
    success, message = setup_pre_commit_hook(git_root)
    print(f"{'✓' if success else '✗'} {message}")

    if not success:
        return 1

    print("\n✓ Setup complete!")
    print("The pre-commit hook will automatically format C files on commit.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
